cls

#region Setting Outlook Anywhere aka RPC over HTTP to be configured with SSL only, and Requiring SSL.

$OA = Get-OutlookAnywhere
$OA | Set-OutlookAnywhere -SSLOffloading $false -InternalClientsRequireSsl $true -ExternalClientsRequireSsl $true
$OAbefore = $OA
$OA = Get-OutlookAnywhere
$OAAfter = $OA

Write-host "Before the change" -ForegroundColor Yellow
$OAbefore

Write-Host "After the change" -ForegroundColor Green
$OAAfter

#endregion Outlook Anywhere configuration

#region Setting Outlook Anywhere Internal and External Hostname with mail.canada.ca

#Getting default values
Get-OutlookAnywhere | ft server, *hostname
<# OUTPUT

Server   ExternalHostname InternalHostname  
------   ---------------- ----------------  
E2016-01                  e2016-01.canada.ca
E2016-02                  e2016-02.canada.ca

#>

# Setting mail.canada.ca

Get-OutlookAnywhere | Set-OutlookAnywhere -InternalHostname mail.canada.ca -InternalClientsRequireSsl $True
#Success !
#Checking the new values:
Get-OutlookAnywhere | ft server, *hostname
<# OUTPUT

Server   ExternalHostname InternalHostname
------   ---------------- ----------------
E2016-01                  mail.canada.ca  
E2016-02                  mail.canada.ca  

#>


#endregion


#region [Optional] Setting SMTP banner as per https://docs.microsoft.com/en-us/exchange/mail-flow/connectors/modify-smtp-banners

$MyRC = Get-ReceiveConnector "E2016-01\Default Frontend E2016-01"

$MyRC | Set-ReceiveConnector -Banner "220 - Ok ... "
# Now try Open Telnet to LocalHost (or E2016-01) on port 25 and see the server starts answering with "220 - Ok ..." 

# Setting SMTP banner back to default
$MyRC | Set-ReceiveConnector -Banner $null
# Now opening Telnet to Localhost (or E2016-01 if you do the test from another machine) on port 25, you'll now get:
# 220 E2016-01.CANADA.CA Microsoft ESMTP MAIL Service ready at Mon, 10 Sep 2018 11:25:04 -0400

#endregion

#region Creating multiple Organization Mailboxes to set multiple Mailbox Servers as OAB Gen mailbox servers
Get-OfflineAddressBook | fl *

<#

https://blogs.technet.microsoft.com/exchange/2012/10/26/oab-in-exchange-server-2013/

In Exchange 2013, the OAB is generated by each Exchange 2013 Mailbox server(s) that hosts a special type of arbitration mailbox, called organization mailbox. OAB generation is not bound by the Server parameter anymore.
#>

#endregion


